name: safety_application
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  mailer: ^5.0.2
#  flutter_mailer: ^2.0.0
  flutter_sms: ^2.3.2
  location: ^4.3.0
  path_provider: ^2.0.0
  firebase_core: ^1.6.0
  fluttertoast: 8.0.7
  cloud_firestore: ^3.1.1
  firebase_auth: ^3.3.0
  image_picker: ^0.8.4
  url_launcher: ^6.0.10
  camera: ^0.9.2
  flutter_phone_direct_caller: ^2.1.0
  telephony: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
